/*
INSERT INTO CUSTOMER VALUES (1,'ASHUTOSH','BANGALORE');
INSERT INTO CUSTOMER VALUES (2,'BODHI','MUMBAI');
INSERT INTO CUSTOMER VALUES (3, 'RANIT','GURGAON');
INSERT INTO CUSTOMER VALUES (4, 'ABHISEKH','KOLKATA');
INSERT INTO CUSTOMER VALUES (5, 'PRATYAY','KOLKATA');
INSERT INTO CUSTOMER VALUES (6, 'SUBHAM','KATHMANDU');
*/
